### ISSUE TITLE
scx_lavd Error: No debugfs mount found

### ISSUE THREAD

**Issue by anh0516** [sched-ext/scx#1502]
I'm looking at `tracepoint_exists()` in `scx_utils`:

`let base_path = tracefs_mount().unwrap_or(debugfs_mount()?);`

It looks like it should be choosing either tracefs or debugfs, whichever succeeds first. I do have tracefs mounted, and that works. But it's still complaining that it can't mount debugfs. I have little familiarity with Rust syntax and I wasn't able to figure out what's going on. Unless I'm completely misunderstanding this, and it's actually checking for both and handling failures for both in one line?

Is debugfs currently used at all or just for tracefs potentially being mounted under it, in which case `tracefs_mount()` should find it anyways?

I was able to get scx_lavd to run again by changing the line to:

`let base_path = tracefs_mount()?;`

and just bypassing checking for a debugfs mount entirely.

**Comment by multics69** [comment]
Thank you @anh0516 for reporting the problem.
I think https://github.com/sched-ext/scx/pull/1500 should fix the problem.
Could you please check if it works on your side?

**Comment by anh0516** [comment]
Forgot to mention that I was building from main. I have already pulled that commit, and it did not fix the problem.

**Comment by multics69** [comment]
Oh, got it.

**Comment by multics69** [comment]
@anh0516 -- Could you post the output of `cat /proc/mounts`?

**Comment by anh0516** [comment]
> [@anh0516](https://github.com/anh0516) -- Could you post the output of `cat /proc/mounts`?

```
/dev/nvme0n1p1 / btrfs rw,noatime,nodiratime,compress-force=zstd:3,ssd,discard=async,space_cache=v2,subvolid=5,subvol=/ 0 0
devtmpfs /dev devtmpfs rw,nosuid,noexec,relatime,size=8088796k,nr_inodes=2022199,mode=755,inode64 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev,inode64 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,nodev,size=3236176k,nr_inodes=819200,mode=755,inode64 0 0
cgroup2 /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot 0 0
efivarfs /sys/firmware/efi/efivars efivarfs rw,nosuid,nodev,noexec,relatime 0 0
bpf /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime,mode=700 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,nosuid,nodev,relatime,pagesize=2M 0 0
tracefs /sys/kernel/tracing tracefs rw,nosuid,nodev,noexec,relatime 0 0
mqueue /dev/mqueue mqueue rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /run/credentials/systemd-journald.service tmpfs ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap 0 0
tmpfs /run/credentials/systemd-resolved.service tmpfs ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap 0 0
tmpfs /tmp tmpfs rw,nosuid,nodev,nr_inodes=1048576,inode64 0 0
/dev/sda3 /games ext4 rw,noatime,nodiratime,discard 0 0
/dev/sda2 /boot ext4 rw,noatime,nodiratime 0 0
/dev/sda1 /boot/efi vfat rw,noatime,nodiratime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=1618084k,nr_inodes=404521,mode=700,uid=1000,gid=1000,inode64 0 0
portal /run/user/1000/doc fuse.portal rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
```

**Comment by multics69** [comment]
Hmm... you have tracefs mounted. Do you have `/sys/kernel/tracing/available_events`?

**Comment by anh0516** [comment]
Yes I do, and it prints traceable events as expected.

**Comment by multics69** [comment]
Hmm... it is strange. I found one bug in the code but in theory it should not affect to your case.
Could you post the result of `grep futex /sys/kernel/tracing/available_events`?

**Comment by multics69** [comment]
@anh0516 -- I submitted a PR (https://github.com/sched-ext/scx/pull/1506). When you have free cycles, please check if the PR works for you.

**Comment by anh0516** [comment]
It works now, thanks.

**Comment by ninetailedtori** [comment]
I'm hitting this issue now:
```
thread 'main' panicked at rust/scx_utils/src/energy_model.rs:239:44:
called `Result::unwrap()` on an `Err` value: No debugfs mount found
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

grep futex on available_events shows the following:
```
syscalls:sys_enter_futex
syscalls:sys_exit_futex
syscalls:sys_enter_futex_waitv
syscalls:sys_exit_futex_waitv
syscalls:sys_enter_futex_wake
syscalls:sys_exit_futex_wake
syscalls:sys_enter_futex_wait
syscalls:sys_exit_futex_wait
syscalls:sys_enter_futex_requeue
syscalls:sys_exit_futex_requeue
```

Using v1.0.15.r5.g929b72d2-1
